package matthew.yelkin.com.halsteadmetrics.jflex;

public enum Token {
    EOL("Конец строки"),
    PLUS("Плюс +"),
    MINUS("Минус -"),
    MULT("Умножить *"),
    DIVIDE("Разделить /"),
    PERCENT("Процент %"),
    LESS("Знак меньше <"),
    MORE("Знак больше >"),
    ASSIGN("Равно ="),
    EQ("Сравнение =="),
    NOT_EQ("Не равно !="),
    EQEQ("Идентичность ==="),
    NOT_EQEQ("Не идентичны !=="),
    L_PAREN("Левая скобка ("),
    R_PAREN("Правая скобка )"),
    LESS_EQ("Меньше либо равно <="),
    MORE_EQ("Больше либо равно >="),
    AND("Логическое И &&"),
    XOR("Xor ^"),
    OR("Логическое ИЛИ ||"),
    L_SHIFT("Сдвиг влево <<"),
    R_SHIFT("Сдвиг вправо >>"),
    CONTAINS(""),
    L_FIGURE("{"),
    R_FIGURE("}"),
    BREAK(""),
    CONTINUE(""),
    SWITCH(""),
    CASE(""),
    DEFAULT(""),
    IF(""),
    ELSE(""),
    REPEAT(""),
    WHILE(""),
    IN(""),
    WHERE(""),
    FOR(""),
    FROM(""),
    QUESTION(""),
    COLON("Двоеточие"),
    ELLIPSIS("Троеточие"),
    ELLIPSIS_LESS(""),
    AS(""),
    DO(""),
    FALLTHROUGH(""),
    NUMBER(""),
    STRING(""),
    IDENTIFIER("Идентификатор"),
    RETURN(""),
    SEMICOLON(""),
    DOT("");

    Token(String description) {
    }
}
