package matthew.yelkin.com.halsteadmetrics.jflex;

public enum Token {
    EOL("Конец строки"),
    PLUS("Плюс +"),
    MINUS("Минус -"),
    MULT("Умножить *"),
    DIVIDE("Разделить /"),
    PERCENT("Процент %"),
    LESS("Знак меньше <"),
    MORE("Знак больше >"),
    ASSIGN("Равно ="),
    EQ("Сравнение =="),
    NOT_EQ("Не равно !="),
    EQEQ("Идентичность ==="),
    NOT_EQEQ("Не идентичны !=="),
    L_PAREN("Левая скобка ("),
    R_PAREN("Правая скобка )"),
    LESS_EQ("Меньше либо равно <="),
    MORE_EQ("Больше либо равно >="),
    AND("Логическое И &&"),
    XOR("Xor ^"),
    OR("Логическое ИЛИ ||"),
    L_SHIFT("Сдвиг влево <<"),
    R_SHIFT("Сдвиг вправо >>"),
    CONTAINS("Проверка содержит"),
    L_FIGURE("{"),
    R_FIGURE("}"),
    L_BRACKET("["),
    R_BRACKET("]"),
    BREAK("Безусловный выход из цикла"),
    CONTINUE("Переход к следующей итерации"),
    SWITCH("Заголовок конструкции выбора"),
    CASE("Ветвь конструкции выбора"),
    DEFAULT("Обычная ветвь конструкции выбора"),
    IF("Если"),
    ELSE("Иначе"),
    REPEAT("Заголовок цикла с постусловием"),
    WHILE("Заголовок цикла с предусловием"),
    IN("Проверка нахождения в множестве"),
    WHERE("Дополнительное условие выбора"),
    FOR("Заголовок цикла с известным количеством повторений"),
    FROM("Из"),
    QUESTION("?"),
    COLON("Двоеточие"),
    ELLIPSIS("Троеточие"),
    ELLIPSIS_LESS(""),
    AS("Как"),
    DO("Делать"),
    FALLTHROUGH("Переход к следующей ветке case"),
    NUMBER("Число"),
    STRING("Строка"),
    IDENTIFIER("Идентификатор"),
    RETURN(""),
    SEMICOLON(""),
    DOT("Точка"),
    COMMA("Запятая"),
    CLASS("Класс"),
    DEINIT(""),
    ENUM("Перечисление"),
    EXTENSION("Расширение"),
    FUNC("Заголовок функции"),
    IMPORT("Импорт"),
    INIT(""),
    LET(""),
    PROTOCOL(""),
    STATIC("Ключевое слово static"),
    STRUCT("Структура"),
    SUBSCRIPT(""),
    TYPEALIAS(""),
    VAR(""),


    DATA_TYPE("Тип данных"),
    BOOL("Истина/ложь"),
    RETURN_TYPE("Возвращаемый тип из функции"),
    ACCESS_MODIFIER("Модификатор доступа")
    ;
    Token(String description) {
    }
}
